### ISSUE TITLE
problem with escrow

### ISSUE THREAD

**Issue by EnVires** [DoctorMcKay/node-steam-tradeoffer-manager#105]
I have i problem with bot 
http://i.imgur.com/Z2myYMI.png screen

code bot :
        offer.getEscrowDuration(function(err, daysTheirEscrow, daysMyEscrow) {
            if (err) logger.error(err);
            else {
                if (daysTheirEscrow != 0) offer.decline(function(err) {
                    if (err) logger.error(err);
                    mysqlConnection.query('INSERT INTO `messages` (`userid`,`msg`,`from`) VALUES (\'' + offer.partner.getSteamID64() + '\',\'У вас не включено мобильное подтверждение!\',\'System\')', function(err, row, fields) {});
                });

**Comment by andrewda** [comment]
Is this a one-time thing or does it happen repeatedly?

**Comment by EnVires** [comment]
several times a day

**Comment by EnVires** [comment]
UP

**Comment by DoctorMcKay** [comment]
So you (a) ignored the guidelines for contributing and (b) bumped your issue after 9 hours. Okay.

**Comment by EnVires** [comment]
sory

**Comment by DoctorMcKay** [comment]
Alright, please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).

In your screenshot, you're getting an error directly from Steam which is "An error was encountered while processing your request:"

That happens when you try to load an invalid trade offer page (e.g. https://steamcommunity.com/tradeoffer/12345). The cause is often that the other party hasn't yet confirmed the trade by email/mobile.

**Comment by EnVires** [comment]
but if you go and see trade,he normal and confirmad

**Comment by DoctorMcKay** [comment]
There's nothing more I can say. That error is coming from Steam.
