### ISSUE TITLE
Potential indefinite growth in _assetCache

### ISSUE THREAD

**Issue by Lagg** [DoctorMcKay/node-steam-tradeoffer-manager#161]
Hi, I've noticed since updating to v2 that there is a slow but definite leak . I've also been trying to debug it because that statement alone is useless obviously. So I used node-heapdump (and cannot give the snapshot because it's highly likely that at least one lib keeps usernames and passwords around in heap, apologies) and poked around.

It appears that `_assetCache` can grow indefinitely. I found this odd at first because I don't ask for descriptions in the relevant parts of the code. Then I saw that there is a call to `_mapItemsToDescriptions` in `createOfferFromData`. This appears to add items to the cache unconditionally, leading to the growth.
 Am I on the right track here, and if so what can be done to maintain this or turn it off completely? Will `manager._assetCache = {};` break things?

**Edit:** That usage of true globals scares me as well. Not related to my issue of course - but its use should strongly be considered due to how easy it is to block GC. I get the usecase. It's hard to negotiate an in-lib shared cache for N+1 clients otherwise. But still :/

**Comment by DoctorMcKay** [comment]
The asset cache more or less grows endlessly by design. Perhaps we could clear entries that are consulted very infrequently, but nobody has reported any issues thus far.

Clearing it yourself by assigning an empty object to `_assetCache` *should* work fine, although you have no guarantees that it'll continue to work fine in the future. Not providing a language should disable the asset cache entirely, in case you don't really need descriptions. If that's not the case, then that's definitely a bug.

**Comment by Lagg** [comment]
Ah okay I wasn't aware that was expected behavior. My initial reason for setting it was to make sure Steam didn't try to be smart and assume a language and then decide to change page formatting based on it or something silly along those lines. But if this would only affect the class info stuff I can find another way to get required data. Thanks.
