### ISSUE TITLE
 Error: Unknown response, eresult: undefined

### ISSUE THREAD

**Issue by Tutyko2016** [DoctorMcKay/node-steam-tradeoffer-manager#169]
New Bugg:

Error: Unknown response, eresult: undefined

How to fix?

**Comment by Tutyko2016** [comment]
error while sending a new trade offer to 765611981925....., retry 30s later, err: Error: Unknown response, eresult: undefined

**Comment by Aareksio** [comment]
I'm quite sure it's a problem with your code, not the module itself.

**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**

**Comment by Tutyko2016** [comment]
Aareksio: i think not. (use same steam-trade-offer-manager version)

**Comment by Aareksio** [comment]
Sorry for bad assumption - the error comes from [TradeOffer.js#L530](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L530)... There's no debug though - maybe logging offer properties (state, id) would help?

Also, checking if the body exists and is an object somewhere near [TradeOffer.js#L480](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L480) might be a good idea.

**Comment by DoctorMcKay** [comment]
What version of `steamcommunity` is installed?

**Comment by Cohedrin** [comment]
Actually just had this happen about 30 minutes ago for the very first time, so safe to say that this is related to some kind of change on steam's side. 

Unfortunately, I don't have the response from steam that caused this to happen, but if It happens again I should have it.

According to the error reporter, @Aareksio is right, the error seems to be coming from [TradeOffer.js#L530](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L480) (actually line 453 for me, because my version is a bit old).

Versions of packages installed:
```
steam	
1.1.0
steam-totp	
1.3.0
steam-tradeoffer-manager	
1.16.4
steam-user	
2.0.3
steamcommunity	
3.18.2
```

**Comment by DoctorMcKay** [comment]
I believe this to be fixed in `steamcommunity`'s 3.23.2 update.

**Comment by Tutyko2016** [comment]
error while sending a new trade offer to 765611981925....., retry 30s later, err: Error: Unknown response, eresult: undefined

You can fix it?

**Comment by DoctorMcKay** [comment]
What version of `steamcommunity` is installed?

**Comment by Tutyko2016** [comment]
3.23.3

**Comment by Tutyko2016** [comment]
today answering if same problem.

**Comment by Tutyko2016** [comment]
thanks works nice!!!
