### ISSUE TITLE
Dont add Items when someone Bet at same time

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steam-tradeoffer-manager#182]
Hey, much times, when more users will put in Items, it eats the items from the first.

`
data:    bot.js:2905 - New offer #1618657312 from 111111111111111111
data:    bot.js:2905 - Offer accepted
data:    bot.js:2905 - Offer #1618657312 changed: Active -> Accepted
data:    bot.js:2905 - Start adding items to round

data:    bot.js:2905 - New offer #1618659199 from 222222222222222222`

There you see, that the "Offer accepted" in 
`manager.on('newOffer', function(offer) {`

Than you see, that this offer changed Active -> Accepted in received Offers...
`manager.on('receivedOfferChanged', function(offer, oldState) {`
a little bit lines later, it will start adding items, but in same time an other user (22222222222222) will add items, and than the first users (11111111111111111) items get eats from bot

What can i do? I dont found anything to say, make one after one...

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**

The problem is mostly likely in your code, not in the module.

**Comment by Marow** [comment]
But anything is wrong but i dont find...

Now i wanted to insert items. 
But in receivedOfferChanged he work to here
`offer.getReceivedItems(function(err, items) {
items.forEach(function(item,i,arr){`

and before items.forEach he stopped... without reason and idk why...
