### ISSUE TITLE
Any possibilities for getUserDetails(callback)

### ISSUE THREAD

**Issue by ylms** [DoctorMcKay/node-steam-tradeoffer-manager#188]
Hello,

The module is getting user details of active trade offers currently. I am be able to get user details of accepted trade offers without module. But I was curious why it is not implemented for module. It would be smooth.

**Comment by DoctorMcKay** [comment]
Because the data from that method is extracted from the trade offer page, which will not load if the offer isn't active (or it was sent by you). The original purpose of this method was to get escrow durations, which are not available elsewhere. If you only need Steam persona data, I recommend that you use the WebAPI instead as it's more stable anyway.
