### ISSUE TITLE
Allow API key to be passed in via options

### ISSUE THREAD

**Issue by scholtzm** [DoctorMcKay/node-steam-tradeoffer-manager#26]
Registering API key is a one time thing. It doesn't expire, ever.

I'd be cool if it was possible to set the key via options so I can skip the HTTP call.
Even slight optimization like this can be useful, considering how unstable Steam is.

**Comment by DoctorMcKay** [comment]
I see no reason to do this. Would you rather perhaps have it retry the call to get the API key a few times?

**Comment by scholtzm** [comment]
No, as I said, I'd like to set the key [here](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/index.js#L39) so that the polling process can start instantly.

**Comment by DoctorMcKay** [comment]
I won't add this as an option, but you can set `apiKey` manually and call `doPoll()` to do what you want. This won't ever be officially supported though.

**Comment by scholtzm** [comment]
Curious to know why, it requires to change 1 line.

According to Wiki, [apiKey](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#apikey) is read only.

**Comment by DoctorMcKay** [comment]
It's not read-only in that it can't be set, It read-only in that setting it is useless. 

The presence of an API key is what the manager uses internally to determine whether it has a web session. That and I don't want to support people who set an API key but not cookies, which will inevitably happen under your suggested feature. 

Plus I find it to be a worthless feature anyway since API key retrieval needs to happen only once per session and is fast.

**Comment by scholtzm** [comment]
```js
var manager = new TradeOfferManager(options);
manager.apiKey = "someKey";
manager.setCookies(...);
```

I suppose this should work without any side effects.

Another possibility would be to pass API key as optional argument in setCookies.
