### ISSUE TITLE
Poll Failure problem

### ISSUE THREAD

**Issue by borianm** [DoctorMcKay/node-steam-tradeoffer-manager#55]
I'm constantly getting poll failure errors and my bot can't work.
The error is: { [Error: socket hang up] code: 'ECONNRESET' }
This happened after the recent updates on most of the scripts I use few days ago. I've updated everything, but it seems like I'm missing something.

node-steam-totp - UPDATED

node-steam-tradeoffer-manager - UPDATED

Any ideas on the fix?

**Comment by DoctorMcKay** [comment]
That's a network problem on your end. Check firewalls and connections.

**Comment by borianm** [comment]
I checked with my support, and they say there's nothing unusual blocking connections. I have tried updating everything to the newest version of node but I still have the same error. What I guess the problem is connecting to Steam Servers but it's just with node-steamcommunity (which is being used in this rep)..Any ideas where else to check for the solution? Maybe change some settings in tradeoffer-manager script or my request settings if possible?

**Comment by DoctorMcKay** [comment]
Something is blocking your HTTP connections to api.steampowered.com. Again, this module is completely and totally not responsible.

Check DNS and firewalls.

**Comment by Paaashka** [comment]
I have experienced that same problem for like two days. As far as i can see this is some kind of ban or limit on the Steam's side. That is not caused by server or network problems, i have one server with two bots running. One has this problem, and another is ok.
According to my observations, this ban is reaction to multiple sessions from same account with Steam. I do not have exact number, but today problem started when my bot lagged and then was trying to reconnect and start session over and over again. I've moved it to another server to bypass authentication ban (is helps sometimes :), bot logged in successfully but with "socket hang up" errors.
Yesterday, i had same problem, and just moving to another IP helped. Today i've tried 4 different IPs, without any result.

After all this, my question is, is there any way to automatically switch manager to interval-based polling, if notifications from Steam does not work?

**Comment by DoctorMcKay** [comment]
You're getting that error in response to polls, not to notifications. And no account-based Steam ban would cause socket hangup errors.

**Comment by Paaashka** [comment]
Okay, then what can the explanation of my problems with only one bot on server can be? Second works just fine.

**Comment by DoctorMcKay** [comment]
Bad network, bad network configuration, etc. Contact your host.

When you're getting the error, see if you can ping steamcommunity.com.

**Comment by Paaashka** [comment]
Yes, i can ping bot steamcommunity.com and api.steamcommunity.com. As i said, i have two almost exact bots on one server and that error appears only on one of them.

**Comment by borianm** [comment]
Finally, someone with the same problem. I dont have any network problems
and i can access both adresses from my server. And I have used pollfailure
to re-login every 2 minutes when steam is down automatically, but now i
think that Steam blocked my server ip.
