### ISSUE TITLE
How to handle offers in new trading system

### ISSUE THREAD

**Issue by joaolucas89** [DoctorMcKay/node-steam-tradeoffer-manager#78]
Doctor McKay, after the new trading system, what has changed about code?

How now do for my bot receive proposals?

Now there must be confirmation(mobile) from both parties and do not know how to handle this, because I see no example anywhere.

Can you give me an explanation?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).**

You can confirm trades using [`node-steamcommunity`](https://github.com/DoctorMcKay/node-steamcommunity).

**Comment by joaolucas89** [comment]
In node-steamcommunity repo, dont have any information about new system :(

**Comment by DoctorMcKay** [comment]
[Please read.](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#getconfirmationstime-key-callback)

**Comment by joaolucas89** [comment]
The big question is, I need to have "two factor" active?

The big question is, I need to have "two factor" active? How do I get the bot receive offers without having the phone to me? I so far have not understood this.

Please Doctor, 2 minutes for me and U will help me a lot ;)

**Comment by joaolucas89** [comment]
I'm senior developer DoctorMcKay, I have another question.

I'm trying to make an application with multiple modules but with only one bot. I wonder how many proposals the bot can receive per second and how many proposals the bot can send per second. Can you answer me that? I will use "queue" to make the system be scalable and there is no loss of performance and so the bot processes one by one.

**Comment by andrewda** [comment]
@joaolucas89 EVERYTHING relating to trade confirmations can be done by node-steamcommunity (read the docs [here](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#getconfirmationstime-key-callback), as @DoctorMcKay already pointed out).

There's no way that you can send more than 1 a second for more than 30 seconds, because there is a 30 trade offer limit IIRC. There is also a 5 trade limit per user. The bot, however, should be capable of receiving a very high number of trade offers per second, as long as you program it well on your end.
