### ISSUE TITLE
Cant cancel or decline a countered offer?

### ISSUE THREAD

**Issue by StevePavlin** [DoctorMcKay/node-steam-tradeoffer-manager#87]
When my bot gets a countered offer, and I attempt to call cancel() or decline() on the offer object, I get this:

Error: Offer #xxxxxxxxx is not active, so it may not be cancelled or declined

It clearly changes to offer state 4 before, is this a bug?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).**

When someone counters a trade offer, the original offer (that you sent) gets marked as Countered, and a *new* trade offer is sent to you, with a new trade offer ID. As such, you can't cancel the original one that you sent since it's no longer active. You can only decline the new one that they send you.
